package com.market.home.entity;

public enum StoreDepartmentName {
    GROCERY_DEPARTMENT, MEAT_DEPARTMENT, SEAFOOD_DEPARTMENT, BEER_AND_WINE_DEPARTMENT, HEALTH_AND_BEAUTY_DEPARTMENT,
    DELI_PREPARED_FOOD_DEPARTMENT, BAKERY
}
